# Increment build counter
set(BUILD_COUNTER_FILE "C:/Users/user/Documents/Development/CPP/FluidNC_gCodeSender/build-mingw/build_counter.txt")
if(EXISTS "${BUILD_COUNTER_FILE}")
    file(READ "${BUILD_COUNTER_FILE}" CURRENT_COUNT)
    string(STRIP "${CURRENT_COUNT}" CURRENT_COUNT)
    if(NOT CURRENT_COUNT MATCHES "^[0-9]+$")
        set(CURRENT_COUNT 0)
    endif()
    math(EXPR NEW_COUNT "${CURRENT_COUNT} + 1")
else()
    set(NEW_COUNT 1)
endif()
file(WRITE "${BUILD_COUNTER_FILE}" "${NEW_COUNT}")
message(STATUS "Build counter incremented to: ${NEW_COUNT}")
